server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: todos
          uri: https://jsonplaceholder.typicode.com/todos/
          predicates:
            - Path=/todos/**

        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/signup, /auth/login
          filters:
            - StripPrefix=1

        - id: auth_self
          uri: http://localhost:8081
          predicates:
            - Path=/auth/self
          filters:
            - StripPrefix=1
            - JwtTokenAuthenticationFilter

        - id: users_public
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
            - Method=GET
          filters:
            - UsernameProxyFilter

        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - JwtTokenAuthenticationFilter

        - id: maps_public
          uri: http://localhost:8082
          predicates:
            - Path=/map/**
            - Method=GET
          filters:
            - UsernameProxyFilter

        - id: maps
          uri: http://localhost:8082
          predicates:
            - Path=/map/**
          filters:
            - JwtTokenAuthenticationFilter

        - id: websocket_route
          uri: ws://localhost:8081
          predicates:
            - Path=/ws/**

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: gateway

security:
  jwt:
    public-key-path: public.cert

